### ISSUE TITLE
`create-ref` feature is inconsistent with the load search behavior and tags the "wrong" commit sometimes.

### ISSUE THREAD

**Issue by mike-schenk** [im-open/git-version-lite#24]
The version calculation code looks at commits from the current working directory's `HEAD` back to the prior applicable sever tag. However, the `create-ref` behavior completely ignores the current `HEAD` and picks the commit to tag based on the current workflow's triggering event. In the case of a pull-request trigger, it _always_ creates that ref against the tip of the pull requests' branch and never the merged result.

This action should either
- not have a `create-ref` feature, or
- create the ref against the same commit on which the next version calculation is based, namely the `HEAD` of the current working directory.

Create-ref behavior:
https://github.com/im-open/git-version-lite/blob/d7329dd29693f8b3aa8de924f988ec9db432e9fc/src/main.js#L25-L28

Version incrementing history search:

https://github.com/im-open/git-version-lite/blob/d7329dd29693f8b3aa8de924f988ec9db432e9fc/src/version.js#L141
https://github.com/im-open/git-version-lite/blob/d7329dd29693f8b3aa8de924f988ec9db432e9fc/src/version.js#L167
https://github.com/im-open/git-version-lite/blob/d7329dd29693f8b3aa8de924f988ec9db432e9fc/src/version.js#L180

**Comment by bradyclifford** [comment]
Could this possible be resolved in #26 ?  @mike-schenk .

If you can provide a small snippet, I can include it in that PR if you would like.

**Comment by bradyclifford** [comment]
Is this what you are referring to?
![image](https://user-images.githubusercontent.com/8923247/216169681-7d9725fc-6f74-4cb0-82ca-64112bb3aa7d.png)

**Comment by mike-schenk** [comment]
> Is this what you are referring to? ![image](https://user-images.githubusercontent.com/8923247/216169681-7d9725fc-6f74-4cb0-82ca-64112bb3aa7d.png)

No, that's something different.

**Comment by danielle-casella-adams** [comment]
The `create-ref` feature will be removed in the next major version in PR #43
